### ISSUE TITLE
Understanding Evaluation using Image-based models (MiniGPT-4 & InstructBLIP)

### ISSUE THREAD

**Issue by amiryanj** [JRDB-dataset/JRDB-Social#1]
Hey @sjahangard 

1) I assume this function is used to draw frames from the video and feed them to the image-based model.  Is that correct?

https://github.com/JRDB-dataset/JRDB-Social/blob/b9b5eeea43339baae8d0d8ed46ed30f421878d71/baselines/MiniGPT-4/infer_jrdb_social.py#L369-L375

2) the `samples` variable is set to `max_trial` which I suppose is equal to the number of ensembles in your experiments. accurate?

3) the image-based model makes a decision on a single frame. correct ?

4) This means in the process of person attribute detection (age, gender, race ...) there might be frames where the target person is `Severely_occluded` or there are multiple people in that frame.

5) For example for the sequence `svl-meeting-gates-2-2019-04-08_0` here are the stats:
*  Fully_visible: 2,994 
* Mostly_visible: 3,401
* Severely_occluded: 4,858
* Fully_occluded: 2,041

which means in more than 50% of the instances the target person is not visible enough.
(that's not the case for all sequences).

Having said that, I'm wondering what if we consider the visibility of the target pedestrian when using image-based models?

**Comment by amiryanj** [comment]
Hey @ControlNet 
Do you have any comment on this?

**Comment by ControlNet** [comment]
> I assume this function is used to draw frames from the video and feed them to the image-based model. Is that correct?

Yes, the MiniGPT-4 is image based MLLM, so need to sample frames from the video input.

> the samples variable is set to max_trial which I suppose is equal to the number of ensembles in your experiments. accurate?

Yes.

> the image-based model makes a decision on a single frame. correct ?

The MiniGPT-4 takes one text query and one image for VQA. In our implementation, ensemble 5 means run inference 5 times, with 5 different frames then majority vote.

> This means in the process of person attribute detection (age, gender, race ...) there might be frames where the target person is 
Severely_occluded or there are multiple people in that frame.

Yes indeed, the sampled frames might not be the optimal frame. It is the naive way how these image-based MLLM work with video. Maybe some preprocessing can improve the video-to-image sampling without losing key information.

> Having said that, I'm wondering what if we consider the visibility of the target pedestrian when using image-based models?

I think it is an interesting idea and worth investigating in the future.

**Comment by amiryanj** [comment]
Hey @ControlNet 

Thanks for your detailed answers.
Here is my calculation on the severity of the occlusions of the pedestrians:

```
Average visibility ratios across all pedestrians on 1312 unique pedestrians [Train Set]:
Fully_visible: 35%
Mostly_visible: 16%
Severely_occluded: 29%
Fully_occluded: 19%
```

My take: 49% of the pedestrian-frames are not visible enough to extract attributes (or they are actually the attributes of another pedestrian). And it surprises me how the MiniGPT model got such high accuracy restults. Am I missing something here?

![acc-train-JRDB-social](https://github.com/user-attachments/assets/e3ae81c6-80eb-4713-9a63-42056e5ff5e5)

**Comment by ControlNet** [comment]
Hi @amiryanj , the Accuracy doesn't tell the full story. If you check the Table 1, you can see the F1 score of MiniGPT-4 is not high (0.7391, 0.2204, 0.2604) for individual level, which means the MiniGPT-4 has bias on the majority categories but ignore the minorities.
